server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/networkprogamming.mailer
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      globally_quoted_identifiers: true
    generate-ddl: true
    show-sql: true
  flyway:
    enabled: false
    driver-class-name: org.mysql.Driver
  main:
    allow-circular-references: true
  # QuocHao config email sender
  mail:
    host: smtp.gmail.com
    port: 587
    username: quochao170402@gmail.com
    password: ohvnvzayvzjwnaaa
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  sql:
    init:
      mode: always
springdoc:
  swagger-ui:
    path: swagger-ui.html
    operationsSorter: method
